import { useEffect, useState } from 'react'
import { socket } from './socket'
import './App.css'

const API = `${import.meta.env.VITE_API_URL || 'http://localhost:3001'}/api`
const money = new Intl.NumberFormat('es-ES', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 })
const damage = { GREEN: ['Menor', 'damage-green'], YELLOW: ['Reparable', 'damage-yellow'], RED: ['Severo', 'damage-red'] }
const labels = { ACTIVE: 'En curso', SCHEDULED: 'Proximamente', ENDED: 'Finalizada', CANCELLED: 'Cancelada' }

function clock(startAt, endAt, serverStatus, now) {
  if (serverStatus === 'CANCELLED') return { status: 'CANCELLED', text: 'Subasta cancelada' }
  const target = now < new Date(startAt) ? new Date(startAt) : new Date(endAt)
  const left = Math.max(0, Math.floor((target - now) / 1000)); const d = Math.floor(left / 86400); const h = Math.floor(left % 86400 / 3600); const m = Math.floor(left % 3600 / 60); const s = left % 60
  const text = `${d}d ${String(h).padStart(2, '0')}h ${String(m).padStart(2, '0')}m ${String(s).padStart(2, '0')}s`
  if (now < new Date(startAt)) return { status: 'SCHEDULED', text: `Inicia en ${text}` }
  if (now >= new Date(endAt)) return { status: 'ENDED', text: 'Subasta cerrada' }
  return { status: serverStatus, text }
}

export default function App() {
  const [vehicles, setVehicles] = useState([]), [catalogs, setCatalogs] = useState({ brands: [] }), [filters, setFilters] = useState({ brand: '', year: '', model: '', fuelType: '', damage: '' }), [selected, setSelected] = useState(null), [user, setUser] = useState(() => JSON.parse(localStorage.getItem('user') || 'null')), [authOpen, setAuthOpen] = useState(false), [page, setPage] = useState('inventory'), [editing, setEditing] = useState(null)
  async function load() { const q = new URLSearchParams(Object.entries(filters).filter(([, v]) => v)).toString(); const r = await fetch(`${API}/vehicles?${q}`); setVehicles(await r.json()) }
  async function open(id) { const r = await fetch(`${API}/vehicles/${id}`); setSelected(await r.json()) }
  useEffect(() => { fetch(`${API}/catalogs`).then((r) => r.json()).then(setCatalogs); load() }, [])
  useEffect(() => { load() }, [filters])
  return <><header className="header"><a className="brand" href="#inicio"><span>SV</span> Subastas de Vehiculos</a><nav><button className="text-button" onClick={() => setPage('inventory')}>Inventario</button>{user && <><button className="text-button" onClick={() => { setEditing(null); setPage('publish') }}>Publicar vehiculo</button><button className="text-button" onClick={() => setPage('mine')}>Mis publicaciones</button></>}</nav>{user ? <div className="profile">Hola, {user.FirstName}<button onClick={() => { localStorage.clear(); setUser(null); setPage('inventory') }}>Salir</button></div> : <button className="outline" onClick={() => setAuthOpen(true)}>Login / Registro</button>}</header><main id="inicio">{page === 'publish' ? (user ? <Publish user={user} editing={editing} done={() => { setPage('mine'); load() }} /> : <Access login={() => setAuthOpen(true)} />) : page === 'mine' ? (user ? <Mine user={user} edit={async (id) => { const r = await fetch(`${API}/vehicles/${id}`); setEditing(await r.json()); setPage('publish') }} /> : <Access login={() => setAuthOpen(true)} />) : <><section className="hero"><div><p className="eyebrow">SUBASTAS VERIFICADAS</p><h1>Tu proximo vehiculo<br /><i>empieza aqui.</i></h1><p className="hero-copy">Inventario seleccionado, historial transparente y pujas seguras en tiempo real.</p></div><div className="hero-visual"><img src="https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=85" alt="Vehiculo deportivo" /></div></section><section className="filters" id="inventario"><div><p className="eyebrow">INVENTARIO</p><h2>Vehiculos disponibles</h2></div><div className="filter-controls">{[['brand','Todas las marcas','brands'],['year','Todos los anos','years'],['model','Todos los modelos','models'],['fuelType','Todo combustible','fuelTypes']].map(([key,label,source]) => <select key={key} value={filters[key]} onChange={(e) => setFilters({ ...filters, [key]: e.target.value })}><option value="">{label}</option>{catalogs[source]?.map((x) => <option key={x}>{x}</option>)}</select>)}<select value={filters.damage} onChange={(e) => setFilters({ ...filters, damage: e.target.value })}><option value="">Todo dano</option>{Object.keys(damage).map((x) => <option key={x} value={x}>{damage[x][0]}</option>)}</select></div></section><VehicleGrid vehicles={vehicles} open={open} /></>}</main>{selected && <Auction vehicle={selected} user={user} close={() => setSelected(null)} login={() => setAuthOpen(true)} refresh={() => open(selected.VehicleID)} reload={load} />}{authOpen && <Auth close={() => setAuthOpen(false)} success={(s) => { localStorage.setItem('token', s.token); localStorage.setItem('user', JSON.stringify(s.user)); setUser(s.user); setAuthOpen(false) }} />}</>
}

function VehicleGrid({ vehicles, open }) { return <section className="grid">{vehicles.map((v) => <article className="vehicle-card" key={v.VehicleID}><div className="image-wrap"><img src={v.CoverImage} alt={`${v.Brand} ${v.Model}`} /><span className={`badge ${damage[v.DamageLevel][1]}`}>Danio {damage[v.DamageLevel][0]}</span></div><div className="card-content"><div className="card-top"><span>{v.Year} · {v.ItemType}</span><span className="auction-state">{labels[v.Status]}</span></div><h3>{v.Brand} {v.Model}</h3><p className="specs">{v.Transmission} · {v.FuelType} · {v.DriveTrain}</p><div className="price-row"><div><small>Oferta actual</small><strong>{money.format(v.CurrentPrice)}</strong></div></div><button className="primary full" onClick={() => open(v.VehicleID)}>Ver subasta</button></div></article>)}</section> }
function Access({ login }) { return <section className="auth"><h2>Acceso requerido</h2><p>Inicia sesion para administrar publicaciones.</p><button className="primary" onClick={login}>Login / Registro</button></section> }

function Mine({ user, edit }) { const [items, setItems] = useState([]), [search, setSearch] = useState(''); useEffect(() => { fetch(`${API}/my-vehicles`, { headers: { Authorization: `Bearer ${localStorage.getItem('token')}` } }).then((r) => r.json()).then(setItems) }, [user.UserID]); const shown = items.filter((v) => `${v.Brand} ${v.Model}`.toLowerCase().includes(search.toLowerCase())); return <section><section className="filters"><div><p className="eyebrow">MIS PUBLICACIONES</p><h2>Vehiculos publicados</h2></div><div className="filter-controls"><input value={search} placeholder="Buscar" onChange={(e) => setSearch(e.target.value)} /></div></section><VehicleGrid vehicles={shown} open={edit} /></section> }

function Publish({ editing, done }) { const [error, setError] = useState(''); const initial = editing ? { year: editing.Year, itemType: editing.ItemType, brand: editing.Brand, model: editing.Model, engine: editing.Engine, transmission: editing.Transmission, fuelType: editing.FuelType, driveTrain: editing.DriveTrain, cylinders: editing.Cylinders, damageLevel: editing.DamageLevel, description: editing.Description || '', basePrice: editing.BasePrice, startAt: editing.StartAt?.slice(0, 16), endAt: editing.EndAt?.slice(0, 16), images: editing.images?.map((x) => x.ImageURL).join('\n') } : {}
  async function submit(e) { e.preventDefault(); const body = Object.fromEntries(new FormData(e.target)); body.images = body.images.split('\n').map((x) => x.trim()).filter(Boolean); const path = editing ? `/vehicles/${editing.VehicleID}` : '/vehicles'; const r = await fetch(`${API}${path}`, { method: editing ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('token')}` }, body: JSON.stringify(body) }); const x = await r.json(); if (!r.ok) return setError(x.error); done() }
  return <form className="auth" onSubmit={submit}><p className="eyebrow">{editing ? 'EDITAR PUBLICACION' : 'PUBLICAR VEHICULO'}</p><h2>{editing ? 'Actualizar vehiculo' : 'Nueva publicacion'}</h2><label>Ano<input name="year" type="number" defaultValue={initial.year} required /></label><label>Tipo de articulo<input name="itemType" defaultValue={initial.itemType} required /></label><div className="two"><label>Marca<input name="brand" defaultValue={initial.brand} required /></label><label>Modelo<input name="model" defaultValue={initial.model} required /></label></div><label>Motor<input name="engine" defaultValue={initial.engine} required /></label><div className="two"><label>Transmision<input name="transmission" defaultValue={initial.transmission} required /></label><label>Combustible<input name="fuelType" defaultValue={initial.fuelType} required /></label></div><div className="two"><label>Traccion<select name="driveTrain" defaultValue={initial.driveTrain} required><option value="">Selecciona</option>{['AWD','FWD','RWD','4WD'].map((x) => <option key={x}>{x}</option>)}</select></label><label>Cilindros<input name="cylinders" type="number" defaultValue={initial.cylinders} required /></label></div><label>Dano<select name="damageLevel" defaultValue={initial.damageLevel} required><option value="">Selecciona</option><option value="GREEN">Verde</option><option value="YELLOW">Amarillo</option><option value="RED">Rojo</option></select></label><label>Descripcion<input name="description" defaultValue={initial.description} /></label><label>URLs de imagen, una por linea (minimo 5)<textarea name="images" defaultValue={initial.images} required /></label><div className="two"><label>Monto base<input name="basePrice" type="number" step="0.01" defaultValue={initial.basePrice} required /></label><label>Inicio<input name="startAt" type="datetime-local" defaultValue={initial.startAt} required /></label></div><label>Cierre<input name="endAt" type="datetime-local" defaultValue={initial.endAt} required /></label>{error && <p className="notice">{error}</p>}<button className="primary full">{editing ? 'Guardar cambios' : 'Publicar vehiculo'}</button></form> }

function Auction({ vehicle, user, close, login, refresh, reload }) {
  const initial = { currentBid: Number(vehicle.CurrentBid ?? vehicle.CurrentPrice), minimumNextBid: Number(vehicle.MinimumNextBid ?? vehicle.CurrentPrice), highestBidderId: vehicle.HighestBidderId, endAt: vehicle.EndAt, status: vehicle.Status }
  const [state, setState] = useState(initial), [amount, setAmount] = useState(initial.minimumNextBid), [participated, setParticipated] = useState(false), [feedback, setFeedback] = useState(''), [now, setNow] = useState(Date.now()), [imageIndex, setImageIndex] = useState(0)
  useEffect(() => { setState(initial); setAmount(initial.minimumNextBid) }, [vehicle.AuctionID])
  useEffect(() => { const id = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(id) }, [])
  useEffect(() => { if (!user) return setParticipated(false); fetch(`${API}/auctions/${vehicle.AuctionID}/participation`, { headers: { Authorization: `Bearer ${localStorage.getItem('token')}` } }).then((r) => r.json()).then((x) => setParticipated(Boolean(x.hasParticipated))) }, [vehicle.AuctionID, user?.UserID])
  useEffect(() => { const update = (x) => { if (+x.auctionId === +vehicle.AuctionID) setState({ currentBid: +x.currentBid, minimumNextBid: +x.minimumNextBid, highestBidderId: x.highestBidderId, endAt: x.endAt, status: x.status }) }; const reconnect = () => { socket.emit('auction:join', vehicle.AuctionID); refresh() }; socket.emit('auction:join', vehicle.AuctionID); socket.on('bid:updated', update); socket.on('connect', reconnect); return () => { socket.emit('auction:leave', vehicle.AuctionID); socket.off('bid:updated', update); socket.off('connect', reconnect) } }, [vehicle.AuctionID])
  useEffect(() => setAmount(state.minimumNextBid), [state.minimumNextBid])
  const timing = clock(vehicle.StartAt, state.endAt, state.status, now), active = timing.status === 'ACTIVE', winning = user && +state.highestBidderId === +user.UserID, outbid = user && participated && !winning
  async function bid(e) { e.preventDefault(); if (!user) return login(); if (!active) return setFeedback(timing.status === 'SCHEDULED' ? 'La subasta aun no ha iniciado.' : 'La subasta esta cerrada.'); const r = await fetch(`${API}/auctions/${vehicle.AuctionID}/bids`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('token')}` }, body: JSON.stringify({ amount: +amount }) }); const x = await r.json(); if (!r.ok) return setFeedback(x.error); setParticipated(true); setState({ currentBid: +x.CurrentBid, minimumNextBid: +x.MinimumNextBid, highestBidderId: x.HighestBidderId, endAt: x.EndAt, status: x.Status }); setFeedback('Tu oferta fue registrada correctamente.'); reload() }
  const images = vehicle.images || []; const main = images[imageIndex]?.ImageURL || vehicle.CoverImage
  return <div className="modal-backdrop" role="dialog" aria-modal="true"><section className="detail"><button className="close" onClick={close}>×</button><div className="gallery"><img src={main} alt={`${vehicle.Brand} ${vehicle.Model}`} /><div className="thumbnails">{images.map((x, index) => <button key={x.SortOrder} type="button" onClick={() => setImageIndex(index)}><img src={x.ImageURL} alt="Vista del vehiculo" /></button>)}</div></div><div className="bid-panel"><span className={`badge ${damage[vehicle.DamageLevel][1]}`}>Danio {damage[vehicle.DamageLevel][0]}</span><h2>{vehicle.Year} {vehicle.Brand}<br />{vehicle.Model}</h2><div className="current"><small>Monto base</small><strong>{money.format(vehicle.BasePrice)}</strong><small>Oferta actual</small><strong>{money.format(state.currentBid)}</strong><span className="countdown">{timing.text}</span></div>{winning && <p className="auction-feedback winning">¡Vas ganando esta subasta!</p>}{outbid && <p className="auction-feedback outbid">Tu oferta ha sido superada. ¡Haz tu oferta ahora antes de que termine el tiempo!</p>}{timing.status === 'SCHEDULED' && <p className="auction-feedback scheduled">Subasta aun no iniciada.</p>}{timing.status === 'ENDED' && <p className="auction-feedback closed">Subasta cerrada.</p>}<form onSubmit={bid}><label>Puja minima siguiente: {money.format(state.minimumNextBid)}</label><div className="bid-input"><input type="number" min={state.minimumNextBid} step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} disabled={!active} /><button className="primary" disabled={!active}>Ofertar</button></div></form>{feedback && <p className="notice">{feedback}</p>}<div className="facts"><span><b>Motor</b>{vehicle.Engine}</span><span><b>Transmision</b>{vehicle.Transmission}</span><span><b>Traccion</b>{vehicle.DriveTrain}</span><span><b>Cilindros</b>{vehicle.Cylinders}</span></div></div></section></div>
}

function Auth({ close, success }) { const [register, setRegister] = useState(false), [error, setError] = useState(''); async function submit(e) { e.preventDefault(); const values = Object.fromEntries(new FormData(e.target)); const r = await fetch(`${API}/auth/${register ? 'register' : 'login'}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) }); const x = await r.json(); if (r.ok) success(x); else setError(x.error) } return <div className="modal-backdrop"><form className="auth" onSubmit={submit}><button type="button" className="close" onClick={close}>×</button><p className="eyebrow">{register ? 'CREAR CUENTA' : 'BIENVENIDO'}</p><h2>{register ? 'Registra tu cuenta' : 'Accede a tu cuenta'}</h2>{register && <div className="two"><label>Nombre<input name="firstName" required /></label><label>Apellido<input name="lastName" required /></label></div>}<label>Correo electronico<input type="email" name="email" required /></label>{register && <label>Telefono<input name="phone" /></label>}<label>Contrasena<input type="password" name="password" minLength="8" required /></label>{error && <p className="notice">{error}</p>}<button className="primary full">{register ? 'Crear cuenta' : 'Iniciar sesion'}</button><button className="text-button" type="button" onClick={() => setRegister(!register)}>{register ? 'Ya tengo una cuenta' : 'Quiero registrarme'}</button></form></div> }
